#!/bin/sh
set -eu

if [ -z "${WORKCARD_APP_DATABASE_PASSWORD:-}" ]; then
  echo "WORKCARD_APP_DATABASE_PASSWORD is required" >&2
  exit 1
fi

psql -v ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" \
  --set=app_password="$WORKCARD_APP_DATABASE_PASSWORD" <<-'SQL'
SELECT format(
    'CREATE ROLE workcard_app LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS',
    :'app_password'
)
WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'workcard_app')
\gexec
SELECT format(
    'ALTER ROLE workcard_app WITH LOGIN PASSWORD %L NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS',
    :'app_password'
)
\gexec
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO workcard_app;
SQL
